### ISSUE TITLE
Didn't support url without protocol prefix

### ISSUE THREAD

**Issue by hanksudo** [r030515495/AlfredTitler#2]
`tr github.com`

<img width="594" alt="screen shot 2016-01-18 at 22 24 00" src="https://cloud.githubusercontent.com/assets/467745/12393680/30ffc960-be32-11e5-819f-380ef6755e4c.png">

**Comment by r030515495** [comment]
i fix that.
please use the new version  Titler v0.9.alfredworkflow.
thanks your feedback.
